### ISSUE TITLE
file structure

### ISSUE THREAD

**Issue by pfinazzo** [ZachDrake/Squad-up#1]
it seems you have a react application inside a folder inside your client directory,

my recommendation is to call the entire project squad-up and make the client directory itself your react application

aka

$ mkdir squad-up
$ cd squad-up 
$ mkdir server
$ create-react-app client

then use concurrently to run both applications (client and server) with one start script on the outside of both directories

both your server and client directories need their own package.jsons with their own specific dependencies/ dev-dependencies

**Comment by ZachDrake** [comment]
Addressed and fixed boss
